### ISSUE TITLE
Alleen maar te zoeken op KVK nummer? 

### ISSUE THREAD

**Issue by renege** [Werkspot/kvk-api#13]
Dus alleen de KVK API Profile geïmplementeerd en niet de KVK API Search? Open voor PR? @LauLaman

**Comment by LauLaman** [comment]
@renege im sorry i no longer work for this company. i believe they accept PRs.
maybe @thijsBreker can help you?

**Comment by thijsBreker** [comment]
@renege Yes, we're more than open for PRs!

**Comment by hgraca** [comment]
This is stale, so I'm gonna close it.

Nevertheless, I confirm what was said before, we are open for PRs.
