### ISSUE TITLE
No Releases (Request for semantic versioning)

### ISSUE THREAD

**Issue by 4c0n** [Werkspot/kvk-api#16]
Hi,

I'd very much like to start using this library. However there are no releases and the original maintainer does not work for your company anymore.

It would be awesome to use Sematic versioning for example, so that we don't have to require the "dev-master" version in our projects.

What needs to be done to release a "v1.0"/stable version?

**Comment by thijsBreker** [comment]
I created a first version v0.1. Our first official stable version :)

**Comment by 4c0n** [comment]
Nice! Thanks Thijs :D
