### ISSUE TITLE
New certificate chain causing issues

### ISSUE THREAD

**Issue by timramakers** [Werkspot/kvk-api#26]
Since today, the new KvK API certificate chain causes issues - a cURL error is returned:

`cURL error 60: Unrecognized Object Identifier. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

I assume this happens for everyone. Message from KvK API Team:

Dear valued costumer,

On September 28, KVK (Chamber of Commerce) will switch to a private root certificate for connecting
to the KVK API Search and KVK API Profile. This implies that all (!) customers need to take immediate
action. An API-key will not be sufficient to provide a connection to the API’s. You need to adapt your
software. This can be achieved by trusting the trust chain in your software.
Instructions can be found https://developers.kvk.nl/guides.

**Comment by LauLaman** [comment]
Hi @timramakers 

I've just opened a PR to address this issue.
When merged you'll be able to configure a certificate to verify the SSL cert with. Or (by default) verification of the SSL cert will be switched off.

Cheers! 🍻

**Comment by LauLaman** [comment]
Still waiting on @thijsBreker to merge the PR
